


#include "fs.h" 



void initflash(void)
{
/*
	gpio_set_mode(BP_FS_MOSI_PORT, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, BP_FS_MOSI_PIN);
//	gpio_set_mode(BP_FS_CS_PORT, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, BP_FS_CS_PIN);
	gpio_set_mode(BP_FS_CS_PORT, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_PUSHPULL, BP_FS_CS_PIN);
	gpio_set_mode(BP_FS_CLK_PORT, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, BP_FS_CLK_PIN);
	gpio_set_mode(BP_FS_MISO_PORT, GPIO_MODE_INPUT, GPIO_CNF_INPUT_FLOAT,BP_FS_MISO_PIN);

*/

}
